version: "3.8"

services:
  db:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: org_chart
      MYSQL_USER: org
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: drogon_app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./coverage_report:/app/coverage_report
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=org
      - DB_PASSWORD=password
      - DB_NAME=org_chart
      - DB_DRIVER=mysql
    working_dir: /app/build
    command: ["../run_docker.sh"]
    stop_grace_period: 30s

  ui:
    image: node:20-alpine
    container_name: ui_app
    working_dir: /app/ui
    ports:
      - "5173:5173"
    volumes:
      - ./UI:/app/ui
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  mysql_data:
